### PR TITLE
Form Validation

### PR DESCRIPTION
**Pull request by audukehinde**
# In this project I implemented form validation using javascript and added the following features:

- When the user submits the form, I check if the email is in lower case.
- If the email is lowercase, the form is sent.
- If the email is not lowercase, an error message is displayed and the form is not sent.

### CODE REVIEW

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# Hi @audukehinde   
Good job so far! Your capstone looks great :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight:
- Good use of gitflow :+1: 

## Required Changes ♻️ 
- [ ]  Your branch has merging conflicts therefore I could not review your project. Please resolve conflicts and ask for another code review where the next reviewer will evaluate your project in-depth


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ignatius22 — CHANGES_REQUESTED** [review]
Hi @audukehinde, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [ ] One of the core requirements for this project is the form validation using javascript,
you did well on getting this done, but for some reason, it is not working on the demo link you provided. Kindly fix this issue and then it can be approved. 


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by audukehinde** [comment]
Hello Reviewer. You should understand that this feature is not working on live demo because I haven't merged this branch. You should clone the project and check from your system

**Comment by audukehinde** [comment]
We only merge when you reviewers approve our project

**Review by SajjadAhmad14 — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:
### Hi Kenny Audu, 
## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏

## Happy Coding 👏👏👏
#### Please leave any questions or comments in the PR if you have any doubts or unclarity!
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
